### PR TITLE
WASI: Access to `EEXIST` through a stub getter function

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Build fix for WASI

### Motivation:

Use of errno values in Swift without libc overlay is not supported with wasi-libc.

https://ci.swift.org/job/oss-swift-pr-test-crosscompile-wasm-ubuntu-20_04/1784/console

```
/home/build-user/swift-testing/Sources/Testing/Attachments/Test.Attachment.swift:249:61: error: cannot find 'EEXIST' in scope
247 |           result = preferredPath
248 |           break
249 |         } catch let error as CError where error.rawValue == EEXIST {
    |                                                             `- error: cannot find 'EEXIST' in scope
250 |           // Try again with a new suffix.
251 |           continue
```

### Modifications:

This change introduces a new function `swt_EEXIST` to get the value of `EEXIST` because it is a complex macro in wasi-libc and cannot be imported directly into Swift.

### Result:

WASI build will be repaired.

### Checklist:

- [ ] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [ ] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Review by grynspan — APPROVED** [review]

**Comment by grynspan** [comment]
Fixes issue introduced in #796.

**Comment by grynspan** [comment]
@kateinoigakukun Seems like the Musl Swift overlay should (re)define these error codes so they're visible to Swift?

**Comment by kateinoigakukun** [comment]
@grynspan The complex errno code definitions exist only in wasi-libc, not in musl. And we already define [these error codes in WASILibc overlay module](https://github.com/swiftlang/swift/blob/e089c5850ed6d11b61353a0a76e2e124746471ef/stdlib/public/Platform/WASILibc.swift.gyb#L67) but not used them here to follow [the porting policy](https://github.com/swiftlang/swift-testing/blob/main/Documentation/Porting.md#including-system-headers)

**Comment by grynspan** [comment]
Fair enough. Just mentioning it in case it wasn't already handled and other projects could run into trouble. :)
