### ISSUE TITLE
Regression in Xcode 26.4: @Test expansion generates invalid code for @SnapshotSuite inside an extension-scoped @Suite

### ISSUE THREAD

**Issue by adammcarter** [swiftlang/swift-testing#1643]
### Description

  I’m seeing what looks like invalid Swift Testing macro expansion in Xcode 26.4 when @Test is generated inside an extension-scoped @Suite.

  This comes from my macros package, swift-snapshot-testing-macros:
  https://github.com/adammcarter/swift-snapshot-testing-macros

  This appears to be a regression: the same package and test target worked under Xcode 26.3, but fail under Xcode 26.4.

  The authored source is valid, but compilation fails in generated @__swiftmacro_*.swift files with diagnostics like:

  - Properties with attribute @used must be static
  - Properties with attribute @section must be static
  - Cannot use instance member '...' within property initializer; property initializers run before 'self' is available
  - Static member '...' cannot be used on instance of type '...'
  - Extensions must not contain stored properties

  The failure appears to be in Swift Testing’s generated code rather than in my handwritten source.

  A representative source file from the repo is:

```swift
import SnapshotTestingMacros
import SwiftUI
import Testing

extension SnapshotTest {

  @Suite
  @SnapshotSuite()
  struct SwiftUIView {

    @SnapshotTest()
    func swiftUiView() -> some View {
      Text("Some SwiftUI text")
    }
  }
}
```

  This is from:
  Tests/SnapshotsIntegrationTests/Views/SwiftUI/SwiftUIView.swift

### Reproduction

  From the swift-snapshot-testing-macros package:

  xcodebuild test \
    -parallel-testing-enabled NO \
    -scheme SnapshotsIntegrationTests \
    -destination 'platform=macOS'

  One concrete authored repro file is:

```swift
  import SnapshotTestingMacros
  import SwiftUI
  import Testing

  extension SnapshotTest {

    @Suite
    @SnapshotSuite()
    struct SwiftUIView {

      @SnapshotTest()
      func swiftUiView() -> some View {
        Text("Some SwiftUI text")
      }
    }
  }
```

  Observed diagnostics in generated source include:

  @__swiftmacro_25SnapshotsIntegrationTests12SnapshotTestV11SwiftUIViewV020swiftUiView_snapshotE00E0fMp_.swift:20:24: error: cannot use instance member '...' within property initializer; property initializers
  run before 'self' is available
  @__swiftmacro_25SnapshotsIntegrationTests12SnapshotTestV11SwiftUIViewV020swiftUiView_snapshotE00E0fMp_.swift:24:1: error: properties with attribute @used must be static
  @__swiftmacro_25SnapshotsIntegrationTests12SnapshotTestV11SwiftUIViewV020swiftUiView_snapshotE00E0fMp_.swift:23:2: error: properties with attribute @section must be static
  @__swiftmacro_25SnapshotsIntegrationTests12SnapshotTestV11SwiftUIViewV020swiftUiView_snapshotE00E0fMp_.swift:3:98: error: static member 'swiftUiView_snapshotTest' cannot be used on instance of type
  'SnapshotTest.SwiftUIView'

  I can also reproduce similar failures from other extension/nested suite shapes in the same repo, for example:

  - Tests/SnapshotsIntegrationTests/SnapshotTest/Traits/Single/SnapshotTest+Traits+Theme+SwiftUI.swift
  - Tests/SnapshotsIntegrationTests/SnapshotTest/Traits/Single/SnapshotTest+Traits+Theme+Inheritance+SwiftUI.swift

### Expected behavior

  Swift Testing macro expansion should generate valid Swift for tests inside extension-scoped and nested suite structures, including cases where a consumer macro expands into @Test-annotated members.

  The package should compile and run the integration target successfully on Xcode 26.4.

### Environment

Xcode 26.4
Build version 17E192
swift-driver version: 1.148.6 Apple Swift version 6.3 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
Target: arm64-apple-macosx26.0
Darwin AT-AL1QF6FC 25.2.0 Darwin Kernel Version 25.2.0: Tue Nov 18 21:09:56 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T6041 arm64

### Additional information

  Public repo:
  https://github.com/adammcarter/swift-snapshot-testing-macros

  Regression note:

  - this repro worked in Xcode 26.3
  - it started failing in Xcode 26.4

  In this repo:

  - swift build passes
  - macro unit tests can be made to pass
  - the integration target still fails because Swift Testing-generated @__swiftmacro_*.swift code is invalid

  The compiler errors consistently point at generated Swift Testing expansion files rather than authored source. The smallest concrete repro I currently have from the repo is the SwiftUIView example above.

  If useful, I can also provide:

  - a stripped-down standalone SwiftPM repro
  - the failing .xcresult
  - the exact generated @__swiftmacro_*.swift snippet from the failing build

**Comment by grynspan** [comment]
Are you able to reproduce this issue without using `@SnapshotSuite` or `@SnapshotTest`, just using Swift Testing API?

**Comment by grynspan** [comment]
I removed the dependency on your macros and rewrote the sample as:

```swift
import SwiftUI
import Testing

struct SnapshotTest {
}

extension SnapshotTest {

  @Suite
  struct SwiftUIView {
    func swiftUiView() -> some View {
      Text("Some SwiftUI text")
    }
  }
}
```

But it did not reproduce the issue.

**Comment by grynspan** [comment]
The issue occurs when your `@SnapshotSuite` and/or `@SnapshotTest` macro expands to include a reference to `@Suite` or `@Test` respectively. The lexical context is empty in the context of the recursive macro expansion, so we cannot see we need to emit the `static` keyword in several places.

**Comment by adammcarter** [comment]
Hi @grynspan thanks for the quick reply! 

The issue https://github.com/swiftlang/swift/issues/79447 is a longstanding one so I'm just trying to track down the difference of Xcode 26.4 as this is the first Xcode version to break

Just did a quick test and Xcode 26.3 is still compiling for me, Xcode 26.4 is still throwing the above errors.

Could this be some regression in Xcode/Macros instead of Swift Testing?

**Comment by grynspan** [comment]
Swift Testing has extensive changes in Swift 6.3 (which ships inside Xcode 26.4) but I am unable to reproduce any issue other than the one in https://github.com/swiftlang/swift/issues/79447. This is perhaps just a new manifestation of it because of our macro changes.

**Comment by adammcarter** [comment]
Sounds like it's going to be an issue in the main Swift repo in that case, keen to start finding out more about this as it currently means my snapshots testing library is unusable in Xcode 26.4

I've prodded for some reviews on my PR to fix the issue you linked to / I opened here: https://github.com/swiftlang/swift/pull/87664

Not sure if you're able to help / point me in any other directions?

Cheers!

**Comment by grynspan** [comment]
Not at this time but I'll ping some colleagues on the Swift compiler team to take a look.

**Comment by adammcarter** [comment]
Thanks @grynspan, much appreciated!

**Comment by adammcarter** [comment]
Hi @grynspan  - was there any updates on this issue?

**Comment by grynspan** [comment]
Not at this time.
