### PR TITLE
Disable pipes code on WASI.

### LINKED ISSUE #698: Conditionalize `pipe(2)` usage for WASI
### Description

WASI does not have `pipe` system call, and wasi-libc doesn't provide any stub for it. So WASI build started failing after https://github.com/swiftlang/swift-testing/pull/694.

```
/home/build-user/swift-testing/Sources/Testing/Support/FileHandle.swift:449:20: error: cannot find 'pipe' in scope
447 |         }
448 | #else
449 |         guard 0 == pipe(fds.baseAddress) else {
    |                    `- error: cannot find 'pipe' in scope
450 |           throw CError(rawValue: swt_errno())
451 |         }
```

https://ci.swift.org/job/oss-swift-pr-test-crosscompile-wasm-ubuntu-20_04/1525/console

### Expected behavior

Conditionalize the use of `pipe(2)` by something like `SWT_NO_PIPE` in swift-testing side.

### Actual behavior

_No response_

### Steps to reproduce

_No response_

### swift-testing version/commit hash

_No response_

### Swift & OS version (output of `swift --version ; uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by grynspan**
WASI does not support pipes.

Resolves #698.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@kateinoigakukun Please assist testing this PR. Thanks!

**Comment by grynspan** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
I verified it builds well on WASI, thanks for your quick fix!

**Comment by grynspan** [comment]
@swift-ci test

**Review by kateinoigakukun — APPROVED** [review]

**Comment by grynspan** [comment]
Thaaaat wasn't the auto-merge button.

Oh well.
