### PR TITLE
Explicitly require Transferable values for attachments also be Sendable

### PR DESCRIPTION
**Pull request by stmontgomery**
This is an attempt to fix a build failure which Swift CI began seeing after the changes in #1519 landed.

Swift CI is [failing](https://github.com/swiftlang/swift-testing/pull/1519#discussion_r3135264435) to build with this change because it's still using Xcode 16.2, but `Transferrable` only gained `Sendable` conformance starting in the OS 26.0 SDK versions. The specific error is:

```
[2026-04-24T01:09:49.272Z] /Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/swift-testing/Sources/Overlays/_Testing_CoreTransferable/Attachments/_AttachableTransferableWrapper.swift:31:15: error: stored property '_transferableValue' of 'Sendable'-conforming generic struct '_AttachableTransferableWrapper' has non-Sendable type 'T'
[2026-04-24T01:09:49.272Z] 27 | /// }
[2026-04-24T01:09:49.272Z] 28 | @available(_transferableAPI, *)
[2026-04-24T01:09:49.272Z] 29 | public struct _AttachableTransferableWrapper<T>: Sendable where T: Transferable {
[2026-04-24T01:09:49.273Z]    |                                              `- note: consider making generic parameter 'T' conform to the 'Sendable' protocol
[2026-04-24T01:09:49.273Z] 30 |   /// The transferable value.
[2026-04-24T01:09:49.273Z] 31 |   private var _transferableValue: T
[2026-04-24T01:09:49.273Z]    |               `- error: stored property '_transferableValue' of 'Sendable'-conforming generic struct '_AttachableTransferableWrapper' has non-Sendable type 'T'
```

So this works around it by making the `Sendable` requirement explicit, rather than relying on the SDK declaration of `Transferable` to state that requirement.

Hopefully this will avoid the need to [revert](https://github.com/swiftlang/swift-testing/pull/1687) the change outright.

Resolves rdar://175478013.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by stmontgomery** [comment]
Kicked off a cross-repo macOS Swift CI build here: https://github.com/swiftlang/swift/pull/79678#issuecomment-4310657853

**Comment by finagolfin** [comment]
Any plans to add the usual full Jenkins CI to this repo? That would have caught this.

**Comment by finagolfin** [comment]
Looks like [this fixed the build in the linked pull's smoke test](https://ci.swift.org/job/swift-PR-macos-smoke-test/27876/console)...

**Comment by grynspan** [comment]
This makes sense.

**Comment by grynspan** [comment]
> Any plans to add the usual full Jenkins CI to this repo? That would have caught this.

We used to have Jenkins-based CI but moved to GHA. Kind of wish we had a workflow that triggered the old Jenkins CI runs for us. (That's a discussion for another thread.)
